function electricalTesting(desiredPowerMargin)

    % Pulls power required and power generated by active components
    [powerReq, numComp1] = sumPropIfOn('PowerRequired', 'ElectricalConsumer', 'ElectricalProfile');
    [powerGen, numComp2] =sumPropIfOn('PowerGenerated', 'ElectricalGenerator', 'ElectricalProfile');

    % Calculates the remaining margin on the electrical system
    powerMargin = (powerGen-powerReq)/powerGen *100
    
    % Displays message based on relation between actual and desired margin
    if (powerMargin) < 0
         disp("Power generated is less than required in this configuration!");
    elseif (powerMargin) < desiredPowerMargin
        disp("The power required does not satisfy the desired power margin is this configuration!");
    elseif (powerMargin) > desiredPowerMargin
        disp("Power is sufficient for this configuration!");

        % Looks to see if the generator are too oversized
        % could change function to determine what is considered oversized
        utilization = powerReq/powerGen *100

        if utilization < 35
            disp("Utilization is below 35%. Consider downsizing the electrical generators.");
        else
            disp("Utilization is acceptable. Proceeding with further analysis.");
        end
    end
end

%[appendix]{"version":"1.0"}
%---
