function result = electricalTesting(desiredPowerMargin)
%ELECTRICALTESTING Electrical generation margin and utilization check.
%   result = electricalTesting(desiredPowerMargin) compares the power
%   generated by active generators that are on with the power required by
%   active consumers that are on. desiredPowerMargin is the required spare
%   generating capacity as a percentage of generation (e.g. 15).
%
%   Prints a verdict and returns a struct with PowerRequired, PowerGenerated
%   (kW), MarginPct = (generated - required) / generated * 100,
%   UtilizationPct = required / generated * 100, and Verdict.
%
%   See also shipmbse.serviceBalance.

arguments
    desiredPowerMargin (1,1) double {mustBeNonnegative}
end

st = shipmbse.config().Stereotypes;
[required, reqDet] = shipmbse.sumProperty(st.ElectricalConsumer + ".PowerRequired", OnlyIfOn=true);
[generated, genDet] = shipmbse.sumProperty(st.ElectricalGenerator + ".PowerGenerated", OnlyIfOn=true);

result = struct("PowerRequired", required, "PowerGenerated", generated, ...
    "MarginPct", NaN, "UtilizationPct", NaN, "Verdict", "");
if ~any(genDet.Included)
    result.Verdict = "No generator is on: no electrical generation.";
elseif ~any(reqDet.Included)
    result.Verdict = "No electrical consumer is on.";
else
    result.MarginPct = (generated - required) / generated * 100;
    result.UtilizationPct = required / generated * 100;
    if result.MarginPct < 0
        result.Verdict = "Power generated is less than power required.";
    elseif result.MarginPct < desiredPowerMargin
        result.Verdict = sprintf("Margin %.1f%% is below the desired %.1f%%.", result.MarginPct, desiredPowerMargin);
    elseif result.UtilizationPct < 35
        result.Verdict = sprintf("Margin met; utilization %.1f%% is below 35%%: consider smaller generators.", ...
            result.UtilizationPct);
    else
        result.Verdict = sprintf("Margin met (%.1f%%); utilization %.1f%%.", result.MarginPct, result.UtilizationPct);
    end
end
fprintf('Required %.1f kW, generated %.1f kW. %s\n', required, generated, result.Verdict);

end
